const GOOGLE_MAPS_API_KEY = 'AIzaSyCCm_xJwgUy6dELucxV_fLTUHeIFPDboDg';
const HERE_MAPS_JAVASCRIPT_API_KEY = 'DMTJa_C2zGaSIIQj6Tw-B6vYO6JzvzbqPQ1P-1cDXWI';
const HERE_MAPS_REST_API_KEY = 'Edp_poBm2QkgoS4Zi20bXPEhNPR93b1Kg0ZGbhEDYgE';
const GOONG_MAPS_MAPTILES_API_KEY = 'DxrhdKGWH5OxebldMbZods1YQA5JDfLvdk9InPtA';
const GOONG_MAPS_API_KEY = 'elPXaBoETpkOddVKSCxcSELCzFtpZngYmtzk9jKk';
